export default {
  login: "2Akki",
id: 93147274,
node_id: "U_kgDOBY1Qig",
avatar_url: "https://avatars.githubusercontent.com/u/93147274?v=4",
gravatar_id: "",
url: "https://api.github.com/users/2Akki",
html_url: "https://github.com/2Akki",
followers_url: "https://api.github.com/users/2Akki/followers",
following_url: "https://api.github.com/users/2Akki/following{/other_user}",
gists_url: "https://api.github.com/users/2Akki/gists{/gist_id}",
starred_url: "https://api.github.com/users/2Akki/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/2Akki/subscriptions",
organizations_url: "https://api.github.com/users/2Akki/orgs",
repos_url: "https://api.github.com/users/2Akki/repos",
events_url: "https://api.github.com/users/2Akki/events{/privacy}",
received_events_url: "https://api.github.com/users/2Akki/received_events",
type: "User",
site_admin: false,
name: "Akki",
company: "HEHEHE Siuuuuu",
blog: "https://temp-app-akki.herokuapp.com/weather",
location: "Eu",
email: null,
hireable: null,
bio: "I am an professional Developer :)",
twitter_username: "Deal_with_Akki",
public_repos: 9,
public_gists: 0,
followers: 1,
following: 1,
created_at: "2021-10-25T15:52:25Z",
updated_at: "2022-05-13T14:32:43Z"
};
