export default [
  {
  "login": "sonny-sharma",
  "id": 83279321,
  "node_id": "MDQ6VXNlcjgzMjc5MzIx",
  "avatar_url": "https://avatars.githubusercontent.com/u/83279321?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/sonny-sharma",
  "html_url": "https://github.com/sonny-sharma",
  "followers_url": "https://api.github.com/users/sonny-sharma/followers",
  "following_url": "https://api.github.com/users/sonny-sharma/following{/other_user}",
  "gists_url": "https://api.github.com/users/sonny-sharma/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/sonny-sharma/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/sonny-sharma/subscriptions",
  "organizations_url": "https://api.github.com/users/sonny-sharma/orgs",
  "repos_url": "https://api.github.com/users/sonny-sharma/repos",
  "events_url": "https://api.github.com/users/sonny-sharma/events{/privacy}",
  "received_events_url": "https://api.github.com/users/sonny-sharma/received_events",
  "type": "User",
  "site_admin": false
  },
  {
    "login": "sonny-sharma",
    "id": 832793212411,
    "node_id": "MDQ6VXNlcjgzMjc5MzIx",
    "avatar_url": "https://avatars.githubusercontent.com/u/83279321?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sonny-sharma",
    "html_url": "https://github.com/sonny-sharma",
    "followers_url": "https://api.github.com/users/sonny-sharma/followers",
    "following_url": "https://api.github.com/users/sonny-sharma/following{/other_user}",
    "gists_url": "https://api.github.com/users/sonny-sharma/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sonny-sharma/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sonny-sharma/subscriptions",
    "organizations_url": "https://api.github.com/users/sonny-sharma/orgs",
    "repos_url": "https://api.github.com/users/sonny-sharma/repos",
    "events_url": "https://api.github.com/users/sonny-sharma/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sonny-sharma/received_events",
    "type": "User",
    "site_admin": false
    },
    {
      "login": "sonny-sharma",
      "id": 832793212313,
      "node_id": "MDQ6VXNlcjgzMjc5MzIx",
      "avatar_url": "https://avatars.githubusercontent.com/u/83279321?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sonny-sharma",
      "html_url": "https://github.com/sonny-sharma",
      "followers_url": "https://api.github.com/users/sonny-sharma/followers",
      "following_url": "https://api.github.com/users/sonny-sharma/following{/other_user}",
      "gists_url": "https://api.github.com/users/sonny-sharma/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sonny-sharma/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sonny-sharma/subscriptions",
      "organizations_url": "https://api.github.com/users/sonny-sharma/orgs",
      "repos_url": "https://api.github.com/users/sonny-sharma/repos",
      "events_url": "https://api.github.com/users/sonny-sharma/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sonny-sharma/received_events",
      "type": "User",
      "site_admin": false
      },
      {
        "login": "sonny-sharma",
        "id": 83279321241,
        "node_id": "MDQ6VXNlcjgzMjc5MzIx",
        "avatar_url": "https://avatars.githubusercontent.com/u/83279321?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sonny-sharma",
        "html_url": "https://github.com/sonny-sharma",
        "followers_url": "https://api.github.com/users/sonny-sharma/followers",
        "following_url": "https://api.github.com/users/sonny-sharma/following{/other_user}",
        "gists_url": "https://api.github.com/users/sonny-sharma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sonny-sharma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sonny-sharma/subscriptions",
        "organizations_url": "https://api.github.com/users/sonny-sharma/orgs",
        "repos_url": "https://api.github.com/users/sonny-sharma/repos",
        "events_url": "https://api.github.com/users/sonny-sharma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sonny-sharma/received_events",
        "type": "User",
        "site_admin": false
        },
        {
          "login": "sonny-sharma",
          "id": 832793212546,
          "node_id": "MDQ6VXNlcjgzMjc5MzIx",
          "avatar_url": "https://avatars.githubusercontent.com/u/83279321?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/sonny-sharma",
          "html_url": "https://github.com/sonny-sharma",
          "followers_url": "https://api.github.com/users/sonny-sharma/followers",
          "following_url": "https://api.github.com/users/sonny-sharma/following{/other_user}",
          "gists_url": "https://api.github.com/users/sonny-sharma/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/sonny-sharma/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/sonny-sharma/subscriptions",
          "organizations_url": "https://api.github.com/users/sonny-sharma/orgs",
          "repos_url": "https://api.github.com/users/sonny-sharma/repos",
          "events_url": "https://api.github.com/users/sonny-sharma/events{/privacy}",
          "received_events_url": "https://api.github.com/users/sonny-sharma/received_events",
          "type": "User",
          "site_admin": false
          }
  ]